### ISSUE TITLE
File permission of webapps

### ISSUE THREAD

**Issue by baldrianbandit** [celogeek/jitsi-meet-arch-unstable#1]
Hi celogeek.

After installing jitsi-meet-web-1.0.4310-1-any.pkg.tar.zst, the file permissions in `/usr/share/webapps/jitsi-meet-web` are set to 660 with ownership root:root. Since nginx runs as user http, the directory is not accessible by default and thus, I set the permissions manually to 644 after install.

May the package set the permissions on install? What'd you consider best practice?

Regards
Alex

**Comment by celogeek** [comment]
Hi,

This should not be like that. That's strange.

I can see in my package this:

```
        find "$DESTDIR" -type f -execdir sed -i "s#${srcdir}##g" "{}" \;
        find "$DESTDIR" -type d -exec chmod 755 {} \;
```

So it touch every files in the package and set the directory to 755.
660 for a directory is very strange, you can't even go inside (missing the +x flag)

Did this happen every time you try to install it?

Also, I start packaging the nightly build for arch: https://aur.archlinux.org/packages/?K=celogeek&SeB=m

The only difference is "jitsi-meet-web" is on arch repo "jitsi-meet". And the meta-package that starts all the services is no more (not the arch way to do package).

I actively maintain this one.

I should update this repos with it as soon as possible.

**Comment by baldrianbandit** [comment]
Sorry, I wasn't clear about that: Only the files have their permissions set to 660 after install. The directories are set to 755.

I installed jitsi-meet-web-1.0.4310-1-any.pkg.tar.zst several times yesterday as I was testing some post install hooks and the permissions were always set like this.

**Comment by celogeek** [comment]
Do you have a custom umask?

Let me check what I got.

**Comment by celogeek** [comment]
I try on a fresh new system
my umask is set to 0022 (default)
then I do in jitsi-meet-web:

```
makepkg -Csfi
```

And here the file permission I have:

<img width="1006" alt="Capture d’écran 2020-08-23 à 01 10 55" src="https://user-images.githubusercontent.com/65178/90967311-abd52780-e4dd-11ea-943c-499a58a11a1c.png">

Can you edit the PKGBUILD and add this (the umask command just after the package()):
```
package() {
        umask 0022
```

if this fix your problem, then you have a default umask set somewhere that make your makepkg became buggy.

**Comment by celogeek** [comment]
can you do a `makepkg -Csf` in the jitsi-meet-web directory and show me a capture of what you have in the pkg dir:

```
ls -l pkg/jitsi-meet-web/usr/share/webapps/jitsi-meet-web/
```

**Comment by baldrianbandit** [comment]
Alright, I'll be checking that out tomorrow when I'm on that machine again.

**Comment by baldrianbandit** [comment]
Checked it on a different machine today and the file permission are definitely set correctly to 644 after installation. Same for the pkg dir:

```
l pkg/jitsi-meet-web/usr/share/webapps/jitsi-meet-web
-rw-r--r-- 1 5.8K Aug 24 14:34 analytics-ga.js
-rw-r--r-- 1 1.6K Aug 24 14:34 app.js
-rw-r--r-- 1   18 Aug 24 14:34 base.html
-rw-r--r-- 1    0 Aug 24 14:34 body.html
-rw-r--r-- 1  324 Aug 24 14:34 ConferenceEvents.js
-rw-r--r-- 1 110K Aug 24 14:34 conference.js
lrwxrwxrwx 1   37 Aug 24 14:34 config.js -> /etc/webapps/jitsi-meet-web/config.js
-rw-r--r-- 1 7.2K Aug 24 14:34 connection.js
drwxr-xr-x 2 4.0K Aug 24 14:34 connection_optimization
drwxr-xr-x 2 4.0K Aug 24 14:34 css
-rw-r--r-- 1 3.6K Aug 24 14:34 favicon.ico
drwxr-xr-x 2 4.0K Aug 24 14:34 fonts
-rw-r--r-- 1    0 Aug 24 14:34 head.html
drwxr-xr-x 2 4.0K Aug 24 14:34 images
-rw-r--r-- 1   32 Aug 24 14:34 index.android.js
-rw-r--r-- 1 7.8K Aug 24 14:34 index.html
-rw-r--r-- 1   32 Aug 24 14:34 index.ios.js
lrwxrwxrwx 1   47 Aug 24 14:34 interface_config.js -> /etc/webapps/jitsi-meet-web/interface_config.js
drwxr-xr-x 2 4.0K Aug 24 14:34 lang
drwxr-xr-x 2 4.0K Aug 24 14:34 libs
-rw-r--r-- 1  13K Aug 24 14:34 LICENSE
lrwxrwxrwx 1   45 Aug 24 14:34 logging_config.js -> /etc/webapps/jitsi-meet-web/logging_config.js
-rw-r--r-- 1  829 Aug 24 14:34 metro.config.js
-rw-r--r-- 1    0 Aug 24 14:34 plugin.head.html
-rw-r--r-- 1   36 Aug 24 14:34 robots.txt
drwxr-xr-x 2 4.0K Aug 24 14:34 sounds
drwxr-xr-x 2 4.0K Aug 24 14:34 static
-rw-r--r-- 1  608 Aug 24 14:34 title.html
-rw-r--r-- 1  12K Aug 24 14:34 webpack.config.js
```

I guess it's all right. Sorry for the inconvenience and thank your for looking into this.

Regards,
Alex
